src/Entity/AboutUs.php
<?php

namespace App\Entity;

use App\Repository\AboutUsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: AboutUsRepository::class)]
class AboutUs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $quote = null;

    #[ORM\Column(length: 1000)]
    private ?string $description = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $thumbnail = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column(length: 1000)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    private ?string $scheduleWeekdays = null;

    #[ORM\Column(length: 255)]
    private ?string $scheduleSat = null;

    #[ORM\Column(length: 255)]
    private ?string $scheduleSun = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(?string $quote): static
    {
        $this->quote = $quote;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?string $thumbnail): static
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getScheduleWeekdays(): ?string
    {
        return $this->scheduleWeekdays;
    }

    public function setScheduleWeekdays(string $scheduleWeekdays): static
    {
        $this->scheduleWeekdays = $scheduleWeekdays;

        return $this;
    }

    public function getScheduleSat(): ?string
    {
        return $this->scheduleSat;
    }

    public function setScheduleSat(string $scheduleSat): static
    {
        $this->scheduleSat = $scheduleSat;

        return $this;
    }

    public function getScheduleSun(): ?string
    {
        return $this->scheduleSun;
    }

    public function setScheduleSun(string $scheduleSun): static
    {
        $this->scheduleSun = $scheduleSun;

        return $this;
    }
}

src/Entity/Promotions.php
<?php

namespace App\Entity;

use App\Repository\PromotionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionsRepository::class)]

class Promotions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $StarDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $EndDate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $Discount = null;

    #[ORM\ManyToMany(targetEntity: services::class, inversedBy: 'promotions')]
    private Collection $services;

    public function __construct()
    {
        $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStarDate(): ?\DateTimeInterface
    {
        return $this->StarDate;
    }

    public function setStarDate(\DateTimeInterface $StarDate): static
    {
        $this->StarDate = $StarDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->EndDate;
    }

    public function setEndDate(?\DateTimeInterface $EndDate): static
    {
        $this->EndDate = $EndDate;

        return $this;
    }

    public function getDiscount(): ?string
    {
        return $this->Discount;
    }

    public function setDiscount(string $Discount): static
    {
        $this->Discount = $Discount;

        return $this;
    }

    /**
     * @return Collection<int, services>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(services $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
        }

        return $this;
    }

    public function removeService(services $service): static
    {
        $this->services->removeElement($service);

        return $this;
    }
}

templates/page/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<section class="cart-page">
		{% if servicesWithForms is not empty %}
			<h1>Mon Panier</h1>
			<form action="{{ path('cart_submit') }}" method="POST">
				<div class="services-container">
					{% for index, item in servicesWithForms %}
						<div class="service-item" data-service-id="{{ item.service.id }}">
							<div class="service-info">
								<div class="info">
									<p>{{ item.service.name }}/ Catégorie Name</p>
									<span>{{ item.service.price }}€</span>
									<span data-service-duration="{{ item.service.duration }}">{{ item.service.duration }}
										minutes</span>
								</div>
								<div class="buttons">
									<a href="#" class="open-calendar">
										<img src="{{ asset('asset/media/icons/calendar.svg') }}" alt="" class="icons-button icons">
									</a>
									<a href="{{ path('cart_remove', {'id': item.service.id}) }}" class="btn btn-danger remove-from-cart-link">
										<img src="{{ asset('asset/media/icons/shopRemove.svg') }}" alt="" class="icons-button icons">
									</a>
								</div>
							</div>
							<div id="calendar-{{ item.service.id }}" class="calendar-options" style="display: none;">
								<h4>Réserver:</h4>
								<div class="calendar-container">
									<div
										class="months">{# Votre code pour les mois ici s'il est nécessaire #}
									</div>
									<div class="week">
										<h2>{{ item.service.name }}</h2>
										<div class="day-slots">
											{% for date, heures in creneauxParService[item.service.id] %}
												<div class="container-day">
													<div class="day">
														{{ heures[0].dayName|trans }}
														{{ heures[0].dayNumber|default('') }}
													</div>

													<div class="available-slots">
														{% set displayedTimeSlots = [] %}

														{% for creneau in heures %}
															{% if creneau.dateSelectTimeSlot >= now|date('Y-m-d') %}
																{% set timeSlotKey = creneau.dateSelectTimeSlot ~ '_' ~ creneau.start %}
																{% if timeSlotKey not in displayedTimeSlots %}
																	{% set displayedTimeSlots = displayedTimeSlots|merge([timeSlotKey]) %}

																	<div class="slot">
																		<input type="radio" id="slot_{{ date }}_{{ creneau.start }}_{{ index }}" name="selectedTimeSlot[{{ item.service.id }}][{{ index }}]" value="{{ creneau.dateSelectTimeSlot }} {{ creneau.start }}">
																		<label for="slot_{{ date }}_{{ creneau.start }}_{{ index }}">{{ creneau.start }}
																			-
																			{{ creneau.end }}</label>
																	</div>
																{% endif %}
															{% endif %}
														{% endfor %}
													</div>
												</div>
											{% endfor %}


										</div>

									</div>
									<div class="btn_submit_form">
										<input type="hidden" name="service_id[{{ index }}]" value="{{ item.service.id }}">
										<button type="submit" class="submit-button">Réserver</button>
										<a class="delete-btn" href="{{ path('cart_remove', {'id': item.service.id}) }}" class="btn btn-danger">Retirer</a>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</form>
			{% else %}
				<p>Votre panier est vide.</p>
			{% endif %}
		</section>


	{% endblock %}

templates/page/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %} Bienvenue, {{ app.user.firstname }}{% endblock %}
{% block description %}Espace utilisateur du site IMS Beauty; consulter vos rendez-vous et modifier vos informations ou supprimer votre compte depuis cette page.{% endblock %}

{% block body %}
	<section class="dashboard">
		<section class="welcome-dashboard">
			<h1>Bienvenue,
				<span>{{ app.user.firstname }}</span>
				!</h1>

			<div class="user-menu">
				<div class="menu">
					<a href="#my-appointments" id="show-appointments">
						<img src="{{asset('asset/media/icons/calendar.svg')}}" alt="Icône calendrier - Afficher Mes Rendez-vous">
						<p>Mes Rendez-vous</p>
					</a>
				</div>
				<div class="menu">
					<a href="#settings" id="show-settings">
						<img src="{{asset('asset/media/icons/settings.svg')}}" alt="Icône paramètres - Mes Paramètres">
						<p>Paramètres</p>
					</a>
				</div>
				<div class="menu">
					<a href="{{path('app_logout')}}">
						<img src="{{asset('asset/media/icons/logOut.svg')}}" alt="Icône Se Déconnecter">
						<p>Se Déconnecter</p>
					</a>
				</div>
			</div>
		</section>

		<section id="my-appointments">
			<div class="upcoming-app">
				<h2>Vos Rendez-vous à venir</h2>
				<div class="app-container">
					{% for appointment in upcomingAppointments %}
                        <div class="appointment">
                            <figure class="datetime">
                                <img src="{{asset('asset/media/icons/deco/agenda.svg')}}" alt="Icône agenda pour rendez-vous">
                                <figcaption>
                                    <p class="date">{{ appointment.getDateTime()|format_datetime(pattern="EEE dd MMM", locale='fr')|replace({'\.': ''})|title }} •
                                        <span class="date-hour">{{ appointment.getDateTime()|date('H:i') }}</span>
                                    </p>
                                </figcaption>
                            </figure>
                            <figure class="service-price">
                                <img src="{{asset('asset/media/icons/deco/chair.svg')}}" alt="Icône décorative - chaise salon de beauté">
                                <figcaption>
								{% for service in appointment.getServices() %}
                                    <p class="service">{{ service.getName() }}
                                        <span class="price">• {{ (service.getPrice() == service.getPrice()|round) ? service.getPrice()|round : service.getPrice() }}€</span>
                                    </p>
								{% endfor %}
                                </figcaption>
                            </figure>
                        </div>
                    {% else %}
                        <p>Vous n'avez pas de rendez-vous à venir.</p>
                    {% endfor %}
				</div>
			</div>
			<div class="past-app">
				<h2>Vos Rendez-vous passer</h2>
				<div class="app-container">
					{% for appointment in pastAppointments %}
                        <div class="appointment">
                            <figure class="datetime">
                                <img src="{{asset('asset/media/icons/deco/agenda.svg')}}" alt="Icône agenda pour rendez-vous">
                                <figcaption>
                                    <p class="date">{{ appointment.getDateTime()|format_datetime(pattern="EEE dd MMM", locale='fr')|replace({'\.': ''})|title }} •
                                        <span class="date-hour">{{ appointment.getDateTime()|date('H:i') }}</span>
                                    </p>
                                </figcaption>
                            </figure>
                            <figure class="service-price">
                                <img src="{{asset('asset/media/icons/deco/chair.svg')}}" alt="Icône décorative - chaise salon de beauté">
                                <figcaption>
								{% for service in appointment.getServices() %}
                                    <p class="service">{{ service.getName() }}
                                        <span class="price">• {{ (service.getPrice() == service.getPrice()|round) ? service.getPrice()|round : service.getPrice() }}€</span>
                                    </p>
								{% endfor %}
                                </figcaption>
                            </figure>
                        </div>
                    {% else %}
                        <p>Vous n'avez pas de rendez-vous à venir.</p>
                    {% endfor %}
				</div>
			</div>
		</section>

		<section id="settings">
			<form action="{{ path('update_user_data') }}" method="POST" class="form-container" id="update-user-form" data-update-url="{{ path('update_user_data') }}">
				{# Insertion du token CSRF pour sécurité, type hidden #}
			    <input type="hidden" name="_token" value="{{ csrf_token('update_user_data') }}">
				<div class="user-names">
					<figure class="form-input">
						<img src="{{ asset('asset/media/icons/deco/lotus.svg') }}" alt="Icône décorative lotus">
						<figcaption>
							<input type="text" placeholder="Nom" name="last_name" value="{{ user.getLastName() }}">
						</figcaption>
					</figure>
					<figure class="form-input">
						<img src="{{ asset('asset/media/icons/deco/lotus.svg') }}" alt="Icône décorative lotus">
						<figcaption>
							<input type="text" placeholder="Prénom" name="first_name" value="{{ user.getFirstName() }}">
						</figcaption>
					</figure>
				</div>

				<figure class="form-input long-input">
					<img src="{{ asset('asset/media/icons/contactPhone.svg') }}" alt="Icône décorative information utilisateur Téléphone">
					<figcaption>
						<input type="text" placeholder="Mobile" name="phone" value="{{ user.getPhone() }}">
					</figcaption>
				</figure>
				<figure class="form-input long-input">
					<img src="{{ asset('asset/media/icons/contactMail.svg') }}" alt="Icône décorative information utilisateur Mail">
					<figcaption>
						<input type="text" placeholder="Email" name="email" value="{{ user.getEmail() }}">
					</figcaption>
					{% if app.user.isVerified %}
					<img src="{{ asset('asset/media/icons/verified.svg') }}" alt="Email vérifiée" class="verify-icon">
					{% else %}
					<img src="{{ asset('asset/media/icons/not-verified.svg') }}" alt="Email non vérifiée" class="verify-icon">
					{% endif %}
				</figure>
				{% if app.user.isVerified %}
					
					{% else %}
					<a href="{{ path('dashboard_resend_verification') }}" class="verification-link">Renvoyer le mail de confirmation</a>
					{% endif %}
				<figure class="form-input long-input">
					<img src="{{ asset('asset/media/icons/calendar.svg') }}" alt="Icône décorative information utilisateur Calendrier">
					<figcaption>
						<input type="date" name="date_of_birth" value="{{ user.getDateOfBith()|date('Y-m-d') }}">
					</figcaption>
				</figure>

				<div class="settings-buttons">
					<button type="submit" class="update-btn" id="update-user-button">Modifier mes données</button>
					<button class="delete-btn">Supprimer mon compte</button>
				</div>
			</form>
		</section>
</section>
{% endblock %}

templates/page/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}IMS Beauty - Insitut de Beauté Viriati{% endblock %}
{% block description %}IMS Beauty, votre salon de beauté à Viriat, offrant des services de qualité pour vos soins et rendez-vous beauté.{% endblock %}

{% block body %}
	<section class="homepage-CTA">
		<figure class="CTA-banner">
			<img src="{{asset('asset/media/banners/skincare-banner.webp')}}" alt="Bannière page d'Accueil - femme recevant un soin du visage. Bien être, masque du visage, soin.">
			<img src="{{asset('asset/media/deco/flower-bg-deco.svg')}}" alt="Fond d'écran décoratif floral" class="banner-deco">
		</figure>

		<div class="cta-ims">
			<figure class="logo-cta">
				<img src="{{asset('asset/media/logo/logoKhakiText.svg')}}" alt="IMS Beauty - Logo couleur texte Alternatif">
				<figcaption>
					<p>Eveillez votre beauté, révélez votre éclat.</p>
				</figcaption>
			</figure>
			<figure class="adress-cta">
				<img src="{{asset('asset/media/icons/contactLocation.svg')}}" alt="Icône de location pour contact">
				<figcaption>
					<p>{{aboutUs.adress}}</p>
				</figcaption>
			</figure>
			<div class="animated-btn btn-two">
				<a href="{{path('app_our_prices')}}">
					<span>Réservez maintenant</span>
					<img src="{{asset('asset/media/icons/deco/lotus.svg')}}" alt="Icône décoratif lotus pour bouton de redirection">
				</a>
			</div>
		</div>
	</section>

	{# INSERT HERE REDUCTION CTA #}
	{% include './components/promotion-box.html.twig' %}
{# INSERT HERE CARDS "SOINS" #}
<section class="homepage-soins">
<h1>Nos Prestations</h1>
    <div class="card-container">
        {% for category in categories %}
            {% if loop.index <= 4 %}
                <div class="category-card">
                    <figure class="category-thumbnail">
                        <img src="{{ asset('asset/media/banners/' ~ category.thumbnail) }}" alt="Banières représentant le soin {{ category.name }} par IMS Beauty" class="category-banner">
                        <figcaption>
                            <h3>{{ category.name }}</h3>
                        </figcaption>
                    </figure>

                    <div class="card-desc">
                        <p>{{ category.description
                            |replace({'<div>': '', '</div>': '', '<br>': 'PLACEHOLDER_BR', '<br/>': 'PLACEHOLDER_BR'})
                            |escape('html')
                            |replace({'PLACEHOLDER_BR': '<br>'})
                            |raw 
                        }}</p>

                        <div class="animated-btn btn-two">
                            <a href="{{ path('category_list_services', {'id': category.id}) }}">
                                <span>Savoir plus</span>
                                <img src="{{ asset('asset/media/icons/deco/lotus.svg') }}" alt="Icône décoratif lotus pour bouton de redirection">
                            </a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
	<a href="{{path('app_categories')}}">Voir plus</a>
</section>
	{# INSERT HERE INSTA FEED COMPO #}
	{% include "./components/insta-feed.html.twig" %}
	{# INSERT HERE IMS BEAUTY DESCRIPTION #}
	{% include "./components/ims-presentation.html.twig" %}

{% endblock %}

templates/page/nos-soins.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Soins chez IMS Beauty{% endblock %}
{% block description %}Venez découvrir notre listes de soins chez IMS Beauty. De manucure aux massage et bien-être nous offrons une large catégories de services pour votre bien-être.{% endblock %}

{% block body %}
{% include './components/page-header.html.twig' with {'page_name': page_name, 'breadcrumbs': breadcrumbs} %}
<section class="category-cards">
	<div class="card-container">
			{% for category in categories %}	
				<div class="category-card">
					<figure class="category-thumbnail">
						<img src="{{ asset('asset/media/banners/' ~ category.thumbnail) }}" alt="Bannière pour {{ category.name }}" class="category-banner">
						<figcaption>
							<h3>{{ category.name }}</h3>
						</figcaption>
					</figure>

					<div class="card-desc">
						<p>{{ category.description
                            |replace({'<div>': '', '</div>': '', '<br>': 'PLACEHOLDER_BR', '<br/>': 'PLACEHOLDER_BR'})
                            |escape('html')
                            |replace({'PLACEHOLDER_BR': '<br>'})
                            |raw 
                        }}</p>

						<div class="animated-btn btn-two">
						<a href="{{ path('category_list_services', {'id': category.id}) }}">
						<span>Savoir plus</span>
						<img src="{{asset('asset/media/icons/deco/lotus.svg')}}" alt="Icône décorative lotus pour bouton de redirection">
					</a>
				</div>
					</div>

				</div>
			{% endfor %}
		</div>
</section>
{% endblock %}

templates/page/nos-tarifs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos tarifs chez IMS Beauty{% endblock %}
{% block description %}Accéder à la listes de nos soins et leurs tarifs directement afin de réservez rapidement et éfficacement.{% endblock %}

{% block body %}
	{% include './components/page-header.html.twig' with {'page_name': page_name, 'breadcrumbs': breadcrumbs} %}
	<section class="tarifs">
		{% for category in categories %}
			<div class="tarif-category">
				<div class="category-header" data-category-id="{{ loop.index }}">
					<div class="category-title">
						<img src="{{asset('asset/media/icons/deco/laurel.svg')}}" alt="Icône décoratif de {{ category.name }}">
						<h2>{{ category.name }}</h2>
					</div>
					<img src="{{asset('asset/media/icons/navigator/minus.svg')}}" alt="Icône symbole pour ouvrir menu des soins" id="icon-{{ loop.index }}" class="icons">
				</div>

				<div id="services-{{ loop.index }}" class="services-container">
					{% for service in category.services %}
						<div class="service-card">
							<img src="{{asset('asset/media/icons/deco/massage-stones.svg')}}" alt="Icône décorative pierres et orchidés massage et bien être" class="icon-desktop">
							{% if service.promotions|length > 0 %}
                        {% set promotion = service.promotions.first() %}
                        	<div class="promotion-info">
								<p>-{{ promotion.discount|round ? promotion.discount|round : promotion.discount }}%</p>
							</div>
                    	{% endif %}
							<div class="service-details">
								<h4>{{ service.name }}</h4>
								<h6>({{ service.duration }} minutes)</h6>
							</div>
							<span>{{ service.price }}€</span>
							<div class="alt-animated-btn">
								<a href="{{path('cart_add', {id: service.id}) }}" class="add-to-cart-link">
									<img src="{{asset('asset/media/icons/shopAdd.svg')}}" alt="Icône panier avec symbole addition pour ajouter ajouter au panier">
								</a>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endfor %}
	</section>
{% endblock %}

templates/page/our_price.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Tarifs
{% endblock %}

{% block body %}
	{% include './components/page-header.html.twig' with {'page_name': page_name, 'breadcrumbs': breadcrumbs} %}
	<section class="tarifs">
		{% for category in categories %}
            <div class="tarif-category">
                <div class="category-header" data-category-id="{{ loop.index }}" onclick="toggleServices('{{ loop.index }}')">
                    <div class="category-title">
                        <img src="{{asset('asset/media/icons/deco/laurel.svg')}}" alt="">
                        <h2>{{ category.name }}</h2>
                    </div>
                    <img src="{{asset('asset/media/icons/navigator/minus.svg')}}" alt="" id="icon-{{ loop.index }}" class="icons">
                </div>
                
				<div id="services-{{ loop.index }}" class="services-container">
                {% for service in category.services %}
                    <div class="service-card">
                        <img src="{{asset('asset/media/icons/deco/massage-stones.svg')}}" alt="" class="icon-desktop">
                        <div class="service-details">
                                <h4>{{ service.name }}</h4>
                                <h6>({{ service.duration }})</h6>
                            <p>{{ service.description }}</p> 
                        </div>
                        <span>{{ service.price }}€</span>
                        <div class="alt-animated-btn">
                            <a href="">
                                <img src="{{asset('asset/media/icons/shopAdd.svg')}}" alt="">
                            </a>
                        </div>
                    </div>
                {% endfor %}
				</div>
            </div>
        {% endfor %}
	</section>
{% endblock %}

templates/page/services-details.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.name }}{% endblock %}
{% block description %}{{ category.description
                            |replace({'<div>': '', '</div>': '' })
                            |escape('html')
                            |raw  }}{% endblock %}

{% block body %}
	{% include './components/page-header.html.twig' with {'page_name': page_name, 'breadcrumbs': breadcrumbs} %}
	<section class="category-row">
		<aside class="category-details-aside">
			<div class="services-liste-container">
				<div class="category-title">
					<h1>{{ category.name }}</h1>
				</div>
				<div class="category-services">
					<ul>
						{% for service in services %}
							<li class="service-name" id="service-name-{{ service.id }}" data-service-id="{{ service.id }}">
								{{ service.name }}
							</li>
						{% else %}
							<p>Aucun service à afficher pour cette catégorie.</p>
						{% endfor %}
					</ul>
				</div>
			</div>
			{# Insérer ici aussi la carte de réduction #}
			{% include './components/promotion-box.html.twig' %}
		</aside>

		<section class="service-details">
			{% for service in services %}
				<div id="service-detail-{{ service.id }}" class="service-detail-content">
					<figure
						class="service-thumbnail">
						{% if service.promotions|length > 0 %}
								{% set promotion = service.promotions.first() %}
								<div class="promotion-info">
									<p>-{{ promotion.discount|round ? promotion.discount|round : promotion.discount }}%</p>
								</div>
							{% endif %}
						{# Check if the service has a thumbnail; if not, use the default image #}
						{% if service.thumbnail %}
							<img src="{{ asset('asset/media/banners/' ~ service.thumbnail) }}" alt="Bannières pour {{ service.name }}">
						{% else %}
							<img src="{{ asset('asset/media/banners/' ~ category.thumbnail) }}" alt="Bannières pour {{ category.name }}">
						{% endif %}
					</figure>
					<div class="service-info">
						<div class="service-name-price">
							<h2>{{ service.name }}</h2>
							<p>{{ service.price }}€</p>
						</div>
						<p class="description-service">
							{{ service.description
                            |replace({'<div>': '', '</div>': '', '<br>': 'PLACEHOLDER_BR', '<br/>': 'PLACEHOLDER_BR'})
                            |escape('html')
                            |replace({'PLACEHOLDER_BR': '<br>'})
                            |raw 
                        }}
						</p>
						<p>Durée :
							<span>{{ service.duration }}</span>
							minutes
						</p>
					</div>
					<div class="animated-btn btn-two">
						<a href="{{path('cart_add', {id: service.id}) }}" class="add-to-cart-link">
							<span>Réservez</span>
							<img src="{{asset('asset/media/icons/deco/lotus.svg')}}" alt="Icône décoratif de lotus pour bouton de redirection">
						</a>
					</div>
				</div>
			{% else %}
				<p>Ce service n'a pas encore de description rédiger.</p>
			{% endfor %}
		</section>
	{% endblock %}